// Shared item data for the electronics listing (index.html) + detail pages (item.html).
// Each item needs a unique `id` (used in item.html?id=...). Edit prices / specs / sold here.
window.ITEMS = [
 {id:"omen-30l", cat:"desk", zh:"惠普 OMEN 30L 游戏主机", en:"HP OMEN 30L Gaming PC", price:850, photo:"",
  cond:"二手良好 / used, good", specs:["Ryzen 7 5800X · RTX 3060 Ti 8G","16G 内存 · 1TB NVMe SSD","一体式水冷 Liquid-cooled · 750W","Windows 11"],
  note:"主机+键鼠，可加显示器 / tower + KB/mouse (monitor available)",
  detail:"高性能游戏主机，八核 5800X + RTX 3060 Ti，静音水冷，1080p/2K 畅玩。可当面测试。A powerful, quiet liquid-cooled gaming PC — great for 1080p/1440p gaming and content creation. Test before you buy.",
  ai:"🤖 <b>本地 AI / Local AI：</b>8G 显存 + CUDA，可本地跑 Llama&nbsp;3 / Qwen2.5 / DeepSeek 等 <b>7–8B 大模型（量化）</b>，以及 Stable Diffusion / SDXL 出图。Runs 7–8B LLMs (Llama 3, Qwen 2.5, DeepSeek, 4-bit) + Stable Diffusion/SDXL locally."},
 {id:"skytech-chronos", cat:"desk", zh:"Skytech Chronos 游戏主机", en:"Skytech Chronos Gaming PC", price:950, photo:"",
  cond:"二手良好 / used, good", specs:["Ryzen 7 3700X · RTX 3070 8G","16G DDR4-3600 · 1TB NVMe","Windows 11"],
  note:"主机+键鼠，可加显示器 / tower + KB/mouse (monitor available)",
  detail:"RTX 3070 游戏主机，2K 高画质流畅。RTX 3070 rig — strong 1080p/1440p gaming.",
  ai:"🤖 <b>本地 AI / Local AI：</b>RTX 3070 (8G) + CUDA，本地跑 Llama&nbsp;3 / Qwen2.5 <b>7–8B（量化）</b>很流畅，Stable Diffusion / SDXL 出图无压力。Smooth local 7–8B LLMs + Stable Diffusion/SDXL image gen."},
 {id:"legion-tower-5i", cat:"desk", zh:"联想 Legion Tower 5i 游戏主机", en:"Lenovo Legion Tower 5i", price:950, photo:"",
  cond:"二手良好 / used, good", specs:["i7-10700 · RTX 3070 8G","16G · 1TB NVMe · 650W","WiFi 6 · Windows 11"],
  note:"主机+键鼠，可加显示器 / tower + KB/mouse (monitor available)",
  detail:"联想品牌机，i7 + RTX 3070，做工扎实，WiFi6。Lenovo-built RTX 3070 gaming desktop, solid build, WiFi 6.",
  ai:"🤖 <b>本地 AI / Local AI：</b>RTX 3070 (8G) + CUDA，可本地运行 Llama&nbsp;3 / Qwen2.5 <b>7–8B（量化）</b> 及 Stable Diffusion / SDXL。RTX 3070 — local 7–8B LLMs + SD/SDXL."},
 {id:"dell-g5-5000", cat:"desk", zh:"戴尔 Dell G5 5000 主机", en:"Dell G5 5000", price:460, photo:"images/g5.jpg",
  cond:"二手良好 / used, good", specs:["i3-10100 · RX 5700 XT 8G","16G · 1TB · Windows 11"],
  note:"含 27寸显示器 + 键鼠 / incl. 27\" monitor + KB/mouse",
  detail:"整套即插即用，含27寸显示器和键鼠，适合1080p游戏。Complete plug-and-play setup incl. a 27\" monitor + keyboard/mouse.",
  ai:"🤖 <b>本地 AI / Local AI：</b>8G 显存，可用 <b>Ollama (Vulkan)</b> 跑 7–8B 模型（AMD 卡，无 CUDA）。8GB — runs 7–8B LLMs via Ollama/Vulkan (AMD card, no CUDA)."},
 {id:"ibuypower-w8700", cat:"desk", zh:"iBUYPOWER 游戏主机 (整套)", en:"iBUYPOWER Gaming PC (complete setup)", price:340, photo:"images/ibuypower-w8700.jpg",
  cond:"二手良好 / used, good", specs:["i7-8700 (6核12线程) · GTX 970 4G","16G DDR4 · 120G SSD","ASUS H310 · Windows 11"],
  note:"含 显示器 + 键鼠 / incl. monitor + KB/mouse",
  detail:"iBUYPOWER 整套即插即用：六核 i7-8700 + GTX 970，含显示器和键鼠，全新装好 Windows 11。适合 1080p 游戏/办公/网课，可当面测试。Complete iBUYPOWER setup — 6-core i7-8700 + GTX 970, incl. monitor + keyboard/mouse, fresh Windows 11. Great for 1080p gaming, office, or school. Test before you buy.",
  ai:"🤖 <b>本地 AI / Local AI：</b>GTX 970 (4G) + CUDA，可本地跑 <b>3–7B 量化模型</b>（Llama&nbsp;3 / Qwen2.5，4-bit）。4GB — runs small 3–7B quantized LLMs locally (CUDA)."},
 {id:"hp-pavilion", cat:"desk", zh:"惠普 Pavilion 主机", en:"HP Pavilion Gaming", price:270, photo:"images/hp1.jpg",
  cond:"二手良好 / used, good", specs:["Ryzen 3 5300G 核显 / iGPU","8G · SSD + HDD · Windows 11"],
  note:"含 显示器 + 键鼠 / incl. monitor + KB/mouse",
  detail:"入门整套，含显示器键鼠，适合办公/网课/轻度游戏。Complete budget setup incl. monitor + KB/mouse — office, school, light gaming."},

 {id:"lenovo-l28u-30", cat:"mon", zh:"联想 L28u-30 显示器", en:"Lenovo L28u-30 Monitor", price:160, photo:"images/lenovo-l28u.jpg",
  cond:"二手良好 / used, good", specs:["28寸 4K UHD IPS","3840×2160 · HDR10 · AMD FreeSync","2× HDMI + DisplayPort"],
  detail:"28寸4K IPS，色彩准，办公娱乐皆宜，无坏点。28\" 4K IPS, accurate colors, no dead pixels. Local pickup."},
 {id:"lg-4k-hdr", cat:"mon", zh:"LG 32UN650K-W 32寸 4K 显示器", en:"LG 32UN650K-W 32\" 4K Monitor", price:250, photo:"images/lg-4k-hdr.jpg",
  cond:"二手 近新 · 2024年9月产 / used, like-new (mfg 09/2024)", specs:["32寸 4K UHD 3840×2160 IPS · 60Hz","HDR10 · DCI-P3 95% · AMD FreeSync","内置音箱 · 可升降底座 · 含19V电源"],
  detail:"LG 32UN650K-W，32寸(31.5) 4K UHD IPS 显示器，HDR10 + 95% DCI-P3 + AMD FreeSync，内置 MaxxAudio 音箱，可升降三边微边框底座。2024年9月生产，近新成色，含原装 19V 电源适配器。海德公园自取。LG 32UN650K-W — 32\" (31.5) 4K UHD IPS, HDR10, 95% DCI-P3, AMD FreeSync, built-in speakers, height-adjustable borderless stand. Manufactured 09/2024, like-new; includes the original 19V power adapter. Local pickup."},

 {id:"rx6700xt", cat:"part", zh:"AMD RX 6700 XT 12G 显卡", en:"AMD Radeon RX 6700 XT 12GB GPU", price:300, photo:"images/rx6700xt.jpg",
  cond:"二手良好 / used, good", specs:["12GB GDDR6 · PCIe 4.0","2K 高刷游戏利器 / strong 1440p","需 8+6pin 供电 · 测试无花屏"],
  detail:"RX 6700 XT 12G，2K 游戏利器，大显存。成色好，测试无花屏。可邮寄(买家付运费)。RX 6700 XT 12GB — excellent 1440p card with lots of VRAM, tested with no artifacts. Can ship at buyer's cost.",
  ai:"🤖 <b>本地 AI / Local AI：</b>12G 显存，用 <b>Ollama (Vulkan)</b> 可跑 7–13B 模型（AMD 卡，无 CUDA）。12GB — runs 7–13B LLMs via Ollama/Vulkan (AMD, no CUDA)."},
 {id:"arctic-lf2-280", cat:"part", zh:"Arctic 一体式水冷 280 (全新)", en:"Arctic Liquid Freezer II 280 (new)", price:110, photo:"images/arctic.jpg",
  cond:"全新未拆 / new, open-box", specs:["280mm 一体式水冷 AIO","全新未使用 · 原盒","送 MX-4 硅脂 / MX-4 incl.","支持 AM4/AM5 · Intel LGA1700/1200/115x"],
  detail:"口碑极佳的280水冷，已停产，全新未用。送MX-4硅脂。可邮寄。Top-rated 280mm AIO, now discontinued — brand new/unused, MX-4 included. Can ship."},
 {id:"zalman-cnps8900", cat:"part", zh:"Zalman CNPS8900 静音风冷 (全新)", en:"Zalman CNPS8900 Quiet cooler (open-box)", price:35, photo:"images/zalman.jpg",
  cond:"全新开盒 / open-box, unused", specs:["静音矮款风冷 low-profile air cooler","全新开盒未使用","仅老平台 old sockets only (非 AM4/AM5/1700)"],
  detail:"全新开盒静音风冷，仅支持老平台(LGA775/115x/1366, AM2/AM3/FM1)，适合老机/复古机。Open-box, never used — older sockets only. Can ship."},
 {id:"razer-invicta", cat:"part", zh:"雷蛇 Razer Invicta 双面鼠标垫 (全新)", en:"Razer Invicta Mercury mouse mat (open-box)", price:50, photo:"",
  cond:"全新未使用 / open-box, never used", specs:["双面硬质游戏鼠标垫 dual-sided hard mat","Speed + Control 双面可选","铝合金底座 · Mercury 白","全新未使用，已停产 / open-box, discontinued"],
  detail:"雷蛇高端双面硬垫，一面Speed一面Control，铝合金底，已停产。全新未拆用。Razer's premium dual-sided (Speed/Control) hard mat, aluminum base — discontinued, open-box & never used. Can ship."},
 {id:"logitech-k540-m510", cat:"part", zh:"罗技 K540 键盘 + M510 鼠标 (无线)", en:"Logitech K540 keyboard + M510 mouse (wireless)", price:20, photo:"",
  cond:"二手 · 成色一般 / used, fair", specs:["无线键鼠套装 · wireless combo","Logitech Unifying 接收器 (一个可连两个)","功能正常，有使用痕迹 / works, cosmetic wear"],
  note:"买任意主机可免费带走 / free with any PC purchase",
  detail:"罗技无线套装：K540 键盘 + M510 鼠标。用过，成色一般但功能正常，含 Unifying 接收器。买主机免费送，也可单独带走。Logitech wireless K540 keyboard + M510 mouse — used, fair cosmetic condition, fully working, Unifying receiver included. Free with any PC purchase, or take them on their own."},

 {id:"seagate-expansion-14tb", cat:"part", zh:"希捷 Expansion 14TB 桌面外置硬盘", en:"Seagate Expansion 14TB External HDD", price:160, photo:"images/seagate-14tb.jpg",
  cond:"二手 · 测试可用 / used, tested working", specs:["14TB · USB 3.0 · 3.5\" 桌面外置","CMR 氦气盘 · 可拆盘 / CMR helium, shuckable","含 12V 电源 + USB 线 / PSU + cable incl.","已测试读写无错误 · USB 外壳不显示 SMART / tested OK; no SMART over USB"],
  note:"可邮寄(买家付运费) / can ship",
  detail:"希捷 Expansion 14TB 桌面外置硬盘 (STEB14000402)，USB 3.0，含原装 12V 电源和数据线。已测试可正常读写、无错误；注意此 USB 外置盒不支持读取 SMART（无法显示通电小时数），可当面测试。适合备份/媒体库/NAS/拆盘。Seagate Expansion 14TB external (STEB14000402), USB 3.0, includes 12V power adapter + cable. Tested working — mounts and reads/writes with no errors; note this USB enclosure doesn't expose SMART (so no power-on-hours readout). Test in person. Great for backups, a media library, NAS, or shucking. Can ship at buyer's cost.",
  ai:""},
 {id:"b550m-ds3h-new", cat:"part", sold:true, zh:"技嘉 B550M DS3H 主板 (全新开盒)", en:"Gigabyte B550M DS3H (open-box, new)", price:70, photo:"images/b550m-ds3h-openbox.jpg",
  cond:"已售出 / sold", specs:["AM4 / B550 Micro-ATX 主板","全新开盒 · 已于 2026-08 售出 / open-box, sold Aug 2026"],
  note:"",
  detail:"技嘉 B550M DS3H，全新开盒从未使用，含原盒、挡板、SATA线、说明书。AM4(锐龙3000/5000)，PCIe 4.0，2×M.2。可邮寄(买家付运费)。Gigabyte B550M DS3H — open box, never used, complete with box / I-O shield / SATA cables / manual. AM4 (Ryzen 3000/5000), PCIe 4.0, 2× M.2. Can ship.",
  ai:""},
 {id:"b550m-ds3h", cat:"part", sold:true, zh:"技嘉 B550M DS3H 主板", en:"Gigabyte B550M DS3H motherboard", price:50, photo:"images/b550m-ds3h.jpg",
  cond:"已售出 / sold", specs:["AM4 / B550 Micro-ATX 主板","已于 2026-08 售出 / sold Aug 2026"]},
];
