// Collectibles & misc listing data (index.html) + detail pages (item.html).
window.ITEMS = [
 {id:"canon-t6i-kit", cat:"misc", zh:"佳能 EOS Rebel T6i 单反套机 (机身 + 3 镜头)", en:"Canon EOS Rebel T6i DSLR kit (body + 3 lenses)", price:550, photo:"images/canon-t6i-kit.jpg",
  cond:"二手有使用痕迹 · 内置闪光灯不稳定 / used, normal wear (built-in flash unreliable)",
  specs:["24MP APS-C 单反 · WiFi · 翻转触屏 / DSLR, Wi-Fi, flip screen","三镜头: EF-S 18-135 变焦 + EF 50/1.8 定焦 + EF-S 10-18 超广角","含 Lowepro Fastpack 250 双肩包 · 2 块电池 + 充电器 / Lowepro backpack + 2 batteries + charger","整套出，适合入门 / complete beginner kit"],
  note:"整套出 · 海德公园自取 / full kit, local pickup",
  detail:"佳能 EOS Rebel T6i 单反整套：24MP APS-C 机身（WiFi、翻转触摸屏）+ 三支镜头（18-135mm 变焦、50mm f/1.8 人像定焦、10-18mm 超广角）+ Lowepro Fastpack 250 双肩包 + 2 块电池和充电器。过去几年偶尔使用、有正常使用痕迹，功能测试可用，适合入门/进阶。<b>注意：内置弹出闪光灯工作不稳定</b>，其余功能正常，建议用自然光或外接闪光灯。海德公园自取，可当面试机。Complete Canon EOS Rebel T6i DSLR kit — 24MP APS-C body (Wi-Fi, flip touchscreen) + three lenses (18-135mm zoom, 50mm f/1.8 portrait prime, 10-18mm ultra-wide) + a Lowepro Fastpack 250 backpack + 2 batteries & charger. Used occasionally over the past few years (normal wear), all tested and working — great for someone getting into photography. <b>Note: the built-in pop-up flash is unreliable</b>; everything else works fine (use natural light or an external flash). Local pickup in Hyde Park; test before you buy."},
 {id:"lego-orchid-10311", cat:"misc", zh:"乐高兰花 (10311) 已拼装", en:"LEGO Icons Orchid (10311), built", price:30, photo:"images/lego-orchid-10311.jpg",
  cond:"已拼装 / 展示成色 built, display condition",
  specs:["乐高植物系列 · 608 颗粒 / Botanical, 608 pcs","橙色定制花 (原版为粉色) / custom ORANGE blooms","免浇水免打理 · 永不凋谢 / no water, no upkeep","约 30cm 高 ~12\" tall"],
  note:"照片里的木底座不含 / the wooden display stand in the photo is NOT included",
  detail:"乐高植物系列兰花 (10311)，已拼装好，摆上桌就是一盆永不凋谢、免打理的花。这一盆是<b>橙色定制配色</b>（乐高原版是粉色），独一份。全新零售约 $50，这个已拼装二手出。海德公园自取，也可小心打包邮寄(买家付运费)。LEGO Botanical Orchid (set 10311), pre-built — a maintenance-free \"plant\" that never needs water or light. This one has <b>custom orange blooms</b> (the stock set is pink), so it's one-of-a-kind. ~$50 new; selling this built one used. Local pickup in Hyde Park; can ship carefully at buyer's cost."},
 {id:"fieldcontrols-trio-plus", cat:"misc", zh:"TRIO Plus 五级空气净化器 (全屋)", en:"TRIO Plus Whole-Home 5-Stage Air Purifier", price:80, photo:"images/fieldcontrols-trio-plus.jpg",
  cond:"近新 · 似未使用 / like-new, appears unused", specs:["5级过滤: 预滤+活性炭+H13 HEPA+UVC+PCO / 5-stage","覆盖约 3300 平方英尺 · 305 CFM / up to 3,300 sq ft","空气质量传感器 + 自动模式 · Energy Star","Costco 全新约 $150 / ~$150 new at Costco"],
  note:"海德公园自取 · 较大件 / local pickup (bulky); 可邮寄买家付运费 / can ship",
  detail:"Costco 购入的 TRIO Plus 全屋五级空气净化器 (Costco 货号 1954355 / Field Controls 602604400)。5级净化：可水洗预滤网 + 活性炭 + H13 真 HEPA (99.97% @ 0.3µm) + UVC 紫外灯 + PCO 除味除气。CADR 305 CFM，可净化最大约 3300 平方英尺的空间。内置空气质量传感器 + 自动模式，Energy Star 节能，安静(最低约25分贝)。<b>滤网塑封似乎从未拆封，几乎全新</b>。Costco 全新约 $150。海德公园自取(较大件)，也可邮寄(买家付运费)。TRIO Plus whole-home 5-stage air purifier from Costco (item 1954355 / Field Controls 602604400). 5 stages: washable pre-filter + activated carbon + H13 True HEPA (99.97% @ 0.3µm) + UVC lamps + PCO for odors/gases. CADR 305 CFM — cleans up to ~3,300 sq ft. Built-in air-quality sensor + Auto mode, Energy Star, quiet (down to ~25 dB). <b>Filters still appear factory-sealed — basically unused.</b> ~$150 new at Costco. Local pickup in Hyde Park (bulky); can ship at buyer's cost."},
 {id:"ikea-kallax-8cube", cat:"misc", zh:"宜家 KALLAX 8格置物架", en:"IKEA KALLAX 8-Cube Shelf", price:40, photo:"images/ikea-kallax.jpg",
  cond:"二手良好 · 桦木色 / used, good — birch/light wood", specs:["4×2 八格 · 147×77cm","结实能装 · 可当隔断 / sturdy, room divider","整体出(刨花板不能拆) / sold assembled"],
  note:"海德公园自取 · 现金/Zelle / local pickup, cash/Zelle",
  detail:"宜家 KALLAX 8格置物架(桦木色)，结实能装，适合书/杂物/黑胶/收纳盒，也可当隔断。整体出(KALLAX 刨花板拆了会松/坏)，海德公园自取。IKEA KALLAX 4x2 (8-cube) shelf in birch/light wood — sturdy; great for books, records, bins, or as a room divider. Sold assembled (particleboard doesn't survive disassembly). Local pickup in Hyde Park."},
 {id:"haier-qtpc05aa", cat:"misc", sold:true, zh:"海尔 5050 BTU 窗式空调", en:"Haier 5,050 BTU Window AC", price:75, photo:"images/haier-qtpc05aa.jpg",
  cond:"已售出 / sold", specs:["5050 BTU · 115V 普通插座","已于 2026-08 售出 / sold Aug 2026"],
  note:"海德公园自取 / local pickup only",
  detail:"海尔窗式空调 5050 BTU，适合卧室/书房/小公寓（约150平方英尺）。普通插座即用，含窗户安装套件，滤网可水洗。制冷正常，成色好。海德公园自取。Haier 5,050 BTU window AC — great for a bedroom / office / small apartment (~150 sq ft). Standard outlet, includes window kit, washable filter. Cold and working. Local pickup in Hyde Park."},
];
