// Collectibles & misc listing data (index.html) + detail pages (item.html).
window.ITEMS = [
 {id:"canon-t6i-kit", cat:"misc", zh:"佳能 EOS Rebel T6i 单反套机 (机身 + 3 镜头)", en:"Canon EOS Rebel T6i DSLR kit (body + 3 lenses)", price:550, photo:"images/canon-t6i-kit.jpg",
  cond:"二手有使用痕迹 · 内置闪光灯不稳定 / used, normal wear (built-in flash unreliable)",
  specs:["24MP APS-C 单反 · WiFi · 翻转触屏 / DSLR, Wi-Fi, flip screen","三镜头: EF-S 18-135 变焦 + EF 50/1.8 定焦 + EF-S 10-18 超广角","含 Lowepro Fastpack 250 双肩包 · 2 块电池 + 充电器 / Lowepro backpack + 2 batteries + charger","整套出，适合入门 / complete beginner kit"],
  note:"整套出 · 海德公园自取 / full kit, local pickup",
  detail:"佳能 EOS Rebel T6i 单反整套：24MP APS-C 机身（WiFi、翻转触摸屏）+ 三支镜头（18-135mm 变焦、50mm f/1.8 人像定焦、10-18mm 超广角）+ Lowepro Fastpack 250 双肩包 + 2 块电池和充电器。过去几年偶尔使用、有正常使用痕迹，功能测试可用，适合入门/进阶。<b>注意：内置弹出闪光灯工作不稳定</b>，其余功能正常，建议用自然光或外接闪光灯。海德公园自取，可当面试机。Complete Canon EOS Rebel T6i DSLR kit — 24MP APS-C body (Wi-Fi, flip touchscreen) + three lenses (18-135mm zoom, 50mm f/1.8 portrait prime, 10-18mm ultra-wide) + a Lowepro Fastpack 250 backpack + 2 batteries & charger. Used occasionally over the past few years (normal wear), all tested and working — great for someone getting into photography. <b>Note: the built-in pop-up flash is unreliable</b>; everything else works fine (use natural light or an external flash). Local pickup in Hyde Park; test before you buy."},
 {id:"lego-orchid-10311", cat:"misc", zh:"乐高兰花 (10311) 已拼装", en:"LEGO Icons Orchid (10311), built", price:30, photo:"images/lego-orchid-10311.jpg",
  cond:"已拼装 / 展示成色 built, display condition",
  specs:["乐高植物系列 · 608 颗粒 / Botanical, 608 pcs","橙色定制花 (原版为粉色) / custom ORANGE blooms","免浇水免打理 · 永不凋谢 / no water, no upkeep","约 30cm 高 ~12\" tall"],
  note:"照片里的木底座不含 / the wooden display stand in the photo is NOT included",
  detail:"乐高植物系列兰花 (10311)，已拼装好，摆上桌就是一盆永不凋谢、免打理的花。这一盆是<b>橙色定制配色</b>（乐高原版是粉色），独一份。全新零售约 $50，这个已拼装二手出。海德公园自取，也可小心打包邮寄(买家付运费)。LEGO Botanical Orchid (set 10311), pre-built — a maintenance-free \"plant\" that never needs water or light. This one has <b>custom orange blooms</b> (the stock set is pink), so it's one-of-a-kind. ~$50 new; selling this built one used. Local pickup in Hyde Park; can ship carefully at buyer's cost."},
 {id:"fieldcontrols-trio-plus", cat:"misc", zh:"TRIO Plus 五级空气净化器 (全屋)", en:"TRIO Plus Whole-Home 5-Stage Air Purifier", price:80, photo:"images/fieldcontrols-trio-plus.jpg",
  cond:"近新 · 似未使用 / like-new, appears unused", specs:["5级过滤: 预滤+活性炭+H13 HEPA+UVC+PCO / 5-stage","覆盖约 3300 平方英尺 · 305 CFM / up to 3,300 sq ft","空气质量传感器 + 自动模式 · Energy Star","Costco 全新约 $150 / ~$150 new at Costco"],
  note:"海德公园自取 · 较大件 / local pickup (bulky); 可邮寄买家付运费 / can ship",
  detail:"Costco 购入的 TRIO Plus 全屋五级空气净化器 (Costco 货号 1954355 / Field Controls 602604400)。5级净化：可水洗预滤网 + 活性炭 + H13 真 HEPA (99.97% @ 0.3µm) + UVC 紫外灯 + PCO 除味除气。CADR 305 CFM，可净化最大约 3300 平方英尺的空间。内置空气质量传感器 + 自动模式，Energy Star 节能，安静(最低约25分贝)。<b>滤网塑封似乎从未拆封，几乎全新</b>。Costco 全新约 $150。海德公园自取(较大件)，也可邮寄(买家付运费)。TRIO Plus whole-home 5-stage air purifier from Costco (item 1954355 / Field Controls 602604400). 5 stages: washable pre-filter + activated carbon + H13 True HEPA (99.97% @ 0.3µm) + UVC lamps + PCO for odors/gases. CADR 305 CFM — cleans up to ~3,300 sq ft. Built-in air-quality sensor + Auto mode, Energy Star, quiet (down to ~25 dB). <b>Filters still appear factory-sealed — basically unused.</b> ~$150 new at Costco. Local pickup in Hyde Park (bulky); can ship at buyer's cost."},
 {id:"thinkpad-x260", cat:"misc", zh:"联想 ThinkPad X260 笔记本 (i7/8G/256G)", en:"Lenovo ThinkPad X260 (i7/8GB/256GB)", price:90, photo:"",
  cond:"二手良好 · 电池老化(~35%) / used, good — weak battery (~35%)", specs:["i7-6600U · 8G · 256G SSD · 12.5\"","经典ThinkPad键盘 · 结实 · 装 Ubuntu","2016机器 · 装不了Win11 · 适合Linux"],
  note:"海德公园自取 或 邮寄(买家付运费) / local or ship",
  detail:"联想 ThinkPad X260 12.5\" 商务本：i7-6600U / 8G / 256G SSD，经典键盘、结实耐用，装 Ubuntu 跑 Linux 很顺。电池老化约 35% 容量、续航短(建议插电或换 ~$30 新电池，可热插拔)；2016 机器装不了 Win11、Win10 已停更，适合 Linux/开发/上网。Lenovo ThinkPad X260 — i7-6600U / 8GB / 256GB, classic keyboard, durable, great Linux laptop. Battery worn (~35%, short runtime — plug in or swap a ~$30 battery); 2016, no Win 11, best for Linux. Local pickup or ship at buyer's cost."},
 {id:"surface-pro-2", cat:"misc", zh:"微软 Surface Pro 2 二合一平板 (i5/4G/128G)", en:"Microsoft Surface Pro 2 (i5/4GB/128GB) + Type Cover", price:50, photo:"images/surface-pro-2.jpg",
  cond:"二手 · 边角掉漆/有划痕 · 西语键盘 / used — edge wear (paint chipped), Spanish keyboard", specs:["i5-4200U · 4G · 128G SSD · 10.6\" 1080p 触屏","含键盘盖(西语)+充电器+原盒 / Type Cover(ES)+charger+box","2013老机 · Win10(已停更) · 适合轻用或Linux"],
  note:"海德公园自取 · 现金/Zelle · 可邮寄(买家付运费)",
  detail:"微软 Surface Pro 2 (2013) 二合一：i5-4200U / 4G / 128G，10.6\" 1080p 触屏带手写笔支持，含键盘盖(西语布局)和充电器。适合轻度上网/看剧/记笔记，或刷个轻量 Linux 当副机。机身有划痕+小磕碰(不影响用)；键盘西语布局(软件可切)；Win10 已停更、装不了 Win11、4G 内存。Microsoft Surface Pro 2 — i5-4200U / 4GB / 128GB, 10.6\" 1080p touch + pen, with Type Cover (Spanish layout) + charger. Good as a light/secondary or Linux tablet. Cosmetic scratch/dent; Spanish keyboard; Win 10 (EOL), no Win 11, 4GB RAM. Local pickup in Hyde Park; can ship at buyer's cost."},
 {id:"dresser-3drawer", cat:"misc", zh:"三斗柜 (桦木色 + 白)", en:"3-Drawer Dresser (birch + white)", price:30, photo:"images/dresser-3drawer.jpg",
  cond:"二手良好 · 右上角轻微泡水 / used — minor water damage top-right corner", specs:["三抽屉 · 桦木色框 + 白面 / 3 drawers","28×16×27 英寸 (宽×深×高) / 28\"W x 16\"D x 27\"H","整体出(刨花板不能拆) / sold assembled"],
  note:"海德公园自取 · 现金/Zelle / local pickup, cash/Zelle",
  detail:"三斗柜，桦木色框 + 白抽屉面，结实、抽拉顺畅。⚠️ 桌面右上角有一点轻微泡水鼓起(仅外观，见图)，其余完好、功能正常。整体出(刨花板不能拆)，海德公园自取。3-drawer dresser — birch frame + white fronts, sturdy, smooth drawers. Minor water swelling on the top-right corner of the top (cosmetic, shown in photos); otherwise good. Sold assembled; local pickup in Hyde Park."},
 {id:"ikea-hemnes-dressing-table", cat:"misc", zh:"宜家 HEMNES 梳妆台带镜子 (白色)", en:"IKEA HEMNES Dressing Table w/ Mirror (white)", price:85, photo:"images/ikea-hemnes-dressing-table.jpg",
  cond:"二手良好 · 白色 · 含玻璃台面保护板 / used, good — white, incl. glass top protector", specs:["椭圆可调角度镜子 + 2 个小抽屉 / oval tilting mirror + 2 drawers","白色 · 弯腿 · 送玻璃台面保护板 / white, curved legs, glass top incl.","整体出 · 海德公园自取(家具不邮寄) / sold assembled, local only"],
  note:"海德公园自取 · 现金/Zelle · 镜子可拆下方便装车 / local pickup, cash/Zelle",
  detail:"宜家 HEMNES 梳妆台(白色)，带椭圆可调角度镜子 + 2 个小抽屉，弯腿造型，优雅。另加了一块玻璃台面保护板(一起送)，桌面不怕刮。成色良好。仅海德公园自取(家具不邮寄)；镜子部分可拆下方便装车。原价约 $149–179。IKEA HEMNES dressing table / vanity in white — oval tilting mirror + two small drawers, curved legs. Includes a glass top protector (bonus — keeps the surface scratch-free). Good used condition. Local pickup only in Hyde Park (furniture, no shipping); the mirror detaches to fit in a car. Retails ~$149–179 new."},
 {id:"ikea-kallax-8cube", cat:"misc", sold:true, zh:"宜家 KALLAX 8格置物架", en:"IKEA KALLAX 8-Cube Shelf", price:40, photo:"images/ikea-kallax.jpg",
  cond:"二手良好 · 桦木色 / used, good — birch/light wood", specs:["4×2 八格 · 147×77cm","结实能装 · 可当隔断 / sturdy, room divider","整体出(刨花板不能拆) / sold assembled"],
  note:"海德公园自取 · 现金/Zelle / local pickup, cash/Zelle",
  detail:"宜家 KALLAX 8格置物架(桦木色)，结实能装，适合书/杂物/黑胶/收纳盒，也可当隔断。整体出(KALLAX 刨花板拆了会松/坏)，海德公园自取。IKEA KALLAX 4x2 (8-cube) shelf in birch/light wood — sturdy; great for books, records, bins, or as a room divider. Sold assembled (particleboard doesn't survive disassembly). Local pickup in Hyde Park."},
 {id:"haier-qtpc05aa", cat:"misc", sold:true, zh:"海尔 5050 BTU 窗式空调", en:"Haier 5,050 BTU Window AC", price:75, photo:"images/haier-qtpc05aa.jpg",
  cond:"已售出 / sold", specs:["5050 BTU · 115V 普通插座","已于 2026-08 售出 / sold Aug 2026"],
  note:"海德公园自取 / local pickup only",
  detail:"海尔窗式空调 5050 BTU，适合卧室/书房/小公寓（约150平方英尺）。普通插座即用，含窗户安装套件，滤网可水洗。制冷正常，成色好。海德公园自取。Haier 5,050 BTU window AC — great for a bedroom / office / small apartment (~150 sq ft). Standard outlet, includes window kit, washable filter. Cold and working. Local pickup in Hyde Park."},
];
